export const kidsWords = {
  family_friends: {
    name: "我的家人和朋友",
    icon: "👨‍👩‍👧‍👦",
    words: [
      { en: "mother", cn: "妈妈" },
      { en: "father", cn: "爸爸" },
      { en: "parents", cn: "父母" },
      { en: "sister", cn: "姐姐/妹妹" },
      { en: "brother", cn: "哥哥/弟弟" },
      { en: "baby", cn: "婴儿" },
      { en: "grandma", cn: "奶奶/外婆" },
      { en: "grandpa", cn: "爷爷/外公" },
      { en: "family", cn: "家庭" },
      { en: "friend", cn: "朋友" },
      { en: "home", cn: "家" },
      { en: "house", cn: "房子" },
      { en: "love", cn: "爱" },
      { en: "hello", cn: "你好" },
      { en: "goodbye", cn: "再见" },
      { en: "name", cn: "名字" },
      { en: "my", cn: "我的" },
      { en: "your", cn: "你的" },
      { en: "our", cn: "我们的" },
      { en: "boy", cn: "男孩" },
      { en: "girl", cn: "女孩" },
      { en: "man", cn: "男人" },
      { en: "woman", cn: "女人" },
      { en: "people", cn: "人们" },
      { en: "hug", cn: "拥抱" },
      { en: "kiss", cn: "亲吻" },
      { en: "play", cn: "玩" },
      { en: "share", cn: "分享" },
      { en: "help", cn: "帮助" },
      { en: "happy", cn: "快乐的" }
    ]
  },
  
  colors_shapes: {
    name: "颜色与形状",
    icon: "🎨",
    words: [
      { en: "red", cn: "红色" },
      { en: "blue", cn: "蓝色" },
      { en: "yellow", cn: "黄色" },
      { en: "green", cn: "绿色" },
      { en: "orange", cn: "橙色" },
      { en: "purple", cn: "紫色" },
      { en: "pink", cn: "粉色" },
      { en: "black", cn: "黑色" },
      { en: "white", cn: "白色" },
      { en: "brown", cn: "棕色" },
      { en: "color", cn: "颜色" },
      { en: "circle", cn: "圆形" },
      { en: "square", cn: "正方形" },
      { en: "triangle", cn: "三角形" },
      { en: "rectangle", cn: "长方形" },
      { en: "star", cn: "星形" },
      { en: "heart", cn: "心形" },
      { en: "oval", cn: "椭圆形" },
      { en: "diamond", cn: "菱形" },
      { en: "big", cn: "大的" },
      { en: "small", cn: "小的" },
      { en: "round", cn: "圆的" },
      { en: "long", cn: "长的" },
      { en: "short", cn: "短的" },
      { en: "find", cn: "找到" },
      { en: "match", cn: "匹配" },
      { en: "draw", cn: "画" },
      { en: "paint", cn: "涂色" },
      { en: "look", cn: "看" },
      { en: "see", cn: "看见" }
    ]
  },
  
  animals: {
    name: "动物世界",
    icon: "🐾",
    words: [
      { en: "cat", cn: "猫" },
      { en: "dog", cn: "狗" },
      { en: "cow", cn: "奶牛" },
      { en: "pig", cn: "猪" },
      { en: "duck", cn: "鸭子" },
      { en: "chicken", cn: "鸡" },
      { en: "sheep", cn: "羊" },
      { en: "horse", cn: "马" },
      { en: "bird", cn: "鸟" },
      { en: "fish", cn: "鱼" },
      { en: "lion", cn: "狮子" },
      { en: "tiger", cn: "老虎" },
      { en: "elephant", cn: "大象" },
      { en: "monkey", cn: "猴子" },
      { en: "giraffe", cn: "长颈鹿" },
      { en: "panda", cn: "熊猫" },
      { en: "bear", cn: "熊" },
      { en: "zoo", cn: "动物园" },
      { en: "farm", cn: "农场" },
      { en: "animal", cn: "动物" },
      { en: "pet", cn: "宠物" },
      { en: "tail", cn: "尾巴" },
      { en: "fur", cn: "毛皮" },
      { en: "wing", cn: "翅膀" },
      { en: "leg", cn: "腿" },
      { en: "walk", cn: "走" },
      { en: "run", cn: "跑" },
      { en: "jump", cn: "跳" },
      { en: "swim", cn: "游泳" },
      { en: "fly", cn: "飞" }
    ]
  },
  
  food_drinks: {
    name: "食物和饮料",
    icon: "🍎",
    words: [
      { en: "apple", cn: "苹果" },
      { en: "banana", cn: "香蕉" },
      { en: "orange", cn: "橙子" },
      { en: "pear", cn: "梨" },
      { en: "grape", cn: "葡萄" },
      { en: "watermelon", cn: "西瓜" },
      { en: "rice", cn: "米饭" },
      { en: "noodle", cn: "面条" },
      { en: "bread", cn: "面包" },
      { en: "egg", cn: "鸡蛋" },
      { en: "milk", cn: "牛奶" },
      { en: "water", cn: "水" },
      { en: "juice", cn: "果汁" },
      { en: "cake", cn: "蛋糕" },
      { en: "candy", cn: "糖果" },
      { en: "ice cream", cn: "冰淇淋" },
      { en: "breakfast", cn: "早餐" },
      { en: "lunch", cn: "午餐" },
      { en: "dinner", cn: "晚餐" },
      { en: "hungry", cn: "饿的" },
      { en: "thirsty", cn: "渴的" },
      { en: "eat", cn: "吃" },
      { en: "drink", cn: "喝" },
      { en: "yummy", cn: "好吃的" },
      { en: "yucky", cn: "难吃的" },
      { en: "hot", cn: "热的" },
      { en: "cold", cn: "冷的" },
      { en: "sweet", cn: "甜的" },
      { en: "fruit", cn: "水果" },
      { en: "vegetable", cn: "蔬菜" }
    ]
  },
  
  body_parts: {
    name: "我的身体",
    icon: "👤",
    words: [
      { en: "head", cn: "头" },
      { en: "hair", cn: "头发" },
      { en: "face", cn: "脸" },
      { en: "eye", cn: "眼睛" },
      { en: "ear", cn: "耳朵" },
      { en: "nose", cn: "鼻子" },
      { en: "mouth", cn: "嘴巴" },
      { en: "tooth", cn: "牙齿" },
      { en: "tongue", cn: "舌头" },
      { en: "arm", cn: "胳膊" },
      { en: "hand", cn: "手" },
      { en: "finger", cn: "手指" },
      { en: "leg", cn: "腿" },
      { en: "foot", cn: "脚" },
      { en: "toe", cn: "脚趾" },
      { en: "body", cn: "身体" },
      { en: "back", cn: "背部" },
      { en: "tummy", cn: "肚子" },
      { en: "bone", cn: "骨头" },
      { en: "tall", cn: "高的" },
      { en: "short", cn: "矮的" },
      { en: "strong", cn: "强壮的" },
      { en: "healthy", cn: "健康的" },
      { en: "touch", cn: "触摸" },
      { en: "clap", cn: "拍手" },
      { en: "stamp", cn: "跺脚" },
      { en: "wave", cn: "挥手" },
      { en: "wash", cn: "洗" },
      { en: "brush", cn: "刷" },
      { en: "feel", cn: "感觉" }
    ]
  },
  
  daily_activities: {
    name: "日常活动",
    icon: "🏃‍♂️",
    words: [
      { en: "get up", cn: "起床" },
      { en: "sleep", cn: "睡觉" },
      { en: "wake up", cn: "醒来" },
      { en: "eat", cn: "吃" },
      { en: "drink", cn: "喝" },
      { en: "play", cn: "玩" },
      { en: "go", cn: "去" },
      { en: "stop", cn: "停止" },
      { en: "run", cn: "跑" },
      { en: "jump", cn: "跳" },
      { en: "sing", cn: "唱歌" },
      { en: "dance", cn: "跳舞" },
      { en: "read", cn: "读" },
      { en: "write", cn: "写" },
      { en: "draw", cn: "画" },
      { en: "brush teeth", cn: "刷牙" },
      { en: "wash face", cn: "洗脸" },
      { en: "put on", cn: "穿上" },
      { en: "take off", cn: "脱下" },
      { en: "clean", cn: "清洁" },
      { en: "help", cn: "帮助" },
      { en: "listen", cn: "听" },
      { en: "look", cn: "看" },
      { en: "say", cn: "说" },
      { en: "talk", cn: "谈话" },
      { en: "walk", cn: "走" },
      { en: "sit", cn: "坐" },
      { en: "stand", cn: "站" },
      { en: "open", cn: "打开" },
      { en: "close", cn: "关闭" }
    ]
  },
};

export const childWords = {
  // 小学阶段词汇
  school_life: {
    name: "我的学校生活",
    icon: "🏫",
    words: [
      { en: "school", cn: "学校" },
      { en: "teacher", cn: "老师" },
      { en: "student", cn: "学生" },
      { en: "class", cn: "班级" },
      { en: "classroom", cn: "教室" },
      { en: "desk", cn: "桌子" },
      { en: "chair", cn: "椅子" },
      { en: "book", cn: "书" },
      { en: "pencil", cn: "铅笔" },
      { en: "pen", cn: "钢笔" },
      { en: "ruler", cn: "尺子" },
      { en: "eraser", cn: "橡皮" },
      { en: "bag", cn: "书包" },
      { en: "homework", cn: "作业" },
      { en: "test", cn: "考试" },
      { en: "question", cn: "问题" },
      { en: "answer", cn: "答案" },
      { en: "read", cn: "读" },
      { en: "write", cn: "写" },
      { en: "listen", cn: "听" },
      { en: "speak", cn: "说" },
      { en: "learn", cn: "学习" },
      { en: "study", cn: "学习" },
      { en: "playground", cn: "操场" },
      { en: "friend", cn: "朋友" },
      { en: "break", cn: "休息" },
      { en: "subject", cn: "科目" },
      { en: "English", cn: "英语" },
      { en: "math", cn: "数学" },
      { en: "art", cn: "美术" }
    ]
  },

  hobbies: {
    name: "我的爱好",
    icon: "🎨",
    words: [
      { en: "hobby", cn: "爱好" },
      { en: "like", cn: "喜欢" },
      { en: "love", cn: "爱" },
      { en: "enjoy", cn: "享受" },
      { en: "interest", cn: "兴趣" },
      { en: "play", cn: "玩" },
      { en: "read", cn: "读" },
      { en: "draw", cn: "画" },
      { en: "paint", cn: "绘画" },
      { en: "sing", cn: "唱歌" },
      { en: "dance", cn: "跳舞" },
      { en: "listen", cn: "听" },
      { en: "music", cn: "音乐" },
      { en: "song", cn: "歌曲" },
      { en: "sport", cn: "运动" },
      { en: "football", cn: "足球" },
      { en: "basketball", cn: "篮球" },
      { en: "swim", cn: "游泳" },
      { en: "run", cn: "跑步" },
      { en: "bike", cn: "自行车" },
      { en: "game", cn: "游戏" },
      { en: "toy", cn: "玩具" },
      { en: "puzzle", cn: "拼图" },
      { en: "film", cn: "电影" },
      { en: "movie", cn: "电影" },
      { en: "TV", cn: "电视" },
      { en: "collect", cn: "收集" },
      { en: "stamp", cn: "邮票" },
      { en: "coin", cn: "硬币" },
      { en: "card", cn: "卡片" }
    ]
  },

  weather_seasons: {
    name: "天气与季节",
    icon: "🌤️",
    words: [
      { en: "weather", cn: "天气" },
      { en: "sunny", cn: "晴朗的" },
      { en: "rainy", cn: "下雨的" },
      { en: "cloudy", cn: "多云的" },
      { en: "windy", cn: "有风的" },
      { en: "snowy", cn: "下雪的" },
      { en: "hot", cn: "热的" },
      { en: "warm", cn: "温暖的" },
      { en: "cool", cn: "凉爽的" },
      { en: "cold", cn: "冷的" },
      { en: "season", cn: "季节" },
      { en: "spring", cn: "春天" },
      { en: "summer", cn: "夏天" },
      { en: "autumn", cn: "秋天" },
      { en: "winter", cn: "冬天" },
      { en: "sun", cn: "太阳" },
      { en: "rain", cn: "雨" },
      { en: "cloud", cn: "云" },
      { en: "wind", cn: "风" },
      { en: "snow", cn: "雪" },
      { en: "umbrella", cn: "雨伞" },
      { en: "coat", cn: "外套" },
      { en: "hat", cn: "帽子" },
      { en: "scarf", cn: "围巾" },
      { en: "glove", cn: "手套" },
      { en: "wear", cn: "穿" },
      { en: "change", cn: "变化" },
      { en: "forecast", cn: "预报" },
      { en: "temperature", cn: "温度" },
      { en: "degree", cn: "度" }
    ]
  },

  home_community: {
    name: "我的家与社区",
    icon: "🏠",
    words: [
      { en: "bedroom", cn: "卧室" },
      { en: "living room", cn: "客厅" },
      { en: "kitchen", cn: "厨房" },
      { en: "bathroom", cn: "浴室" },
      { en: "garden", cn: "花园" },
      { en: "park", cn: "公园" },
      { en: "supermarket", cn: "超市" },
      { en: "shop", cn: "商店" },
      { en: "library", cn: "图书馆" },
      { en: "hospital", cn: "医院" },
      { en: "police station", cn: "警察局" },
      { en: "fire station", cn: "消防站" },
      { en: "street", cn: "街道" },
      { en: "road", cn: "道路" },
      { en: "near", cn: "近的" },
      { en: "far", cn: "远的" },
      { en: "left", cn: "左边" },
      { en: "right", cn: "右边" },
      { en: "front", cn: "前面" },
      { en: "back", cn: "后面" },
      { en: "between", cn: "在...之间" },
      { en: "next to", cn: "在...旁边" },
      { en: "opposite", cn: "对面" },
      { en: "place", cn: "地方" },
      { en: "building", cn: "建筑物" },
      { en: "city", cn: "城市" },
      { en: "town", cn: "城镇" },
      { en: "village", cn: "村庄" },
      { en: "neighbor", cn: "邻居" }
    ]
  },

  festivals_celebrations: {
    name: "节日与庆祝",
    icon: "🎉",
    words: [
      { en: "festival", cn: "节日" },
      { en: "holiday", cn: "假期" },
      { en: "birthday", cn: "生日" },
      { en: "Christmas", cn: "圣诞节" },
      { en: "Spring Festival", cn: "春节" },
      { en: "party", cn: "聚会" },
      { en: "celebrate", cn: "庆祝" },
      { en: "decoration", cn: "装饰" },
      { en: "gift", cn: "礼物" },
      { en: "present", cn: "礼物" },
      { en: "card", cn: "卡片" },
      { en: "cake", cn: "蛋糕" },
      { en: "candle", cn: "蜡烛" },
      { en: "song", cn: "歌曲" },
      { en: "dance", cn: "舞蹈" },
      { en: "food", cn: "食物" },
      { en: "family", cn: "家庭" },
      { en: "friend", cn: "朋友" },
      { en: "happy", cn: "快乐的" },
      { en: "fun", cn: "有趣的" },
      { en: "tradition", cn: "传统" },
      { en: "custom", cn: "习俗" },
      { en: "wear", cn: "穿" },
      { en: "special", cn: "特别的" },
      { en: "time", cn: "时间" },
      { en: "wish", cn: "愿望" },
      { en: "hope", cn: "希望" },
      { en: "invite", cn: "邀请" },
      { en: "guest", cn: "客人" },
      { en: "lucky money", cn: "压岁钱" }
    ]
  },

  plans_arrangements: {
    name: "计划与安排",
    icon: "📅",
    words: [
      { en: "plan", cn: "计划" },
      { en: "going to", cn: "将要" },
      { en: "will", cn: "将会" },
      { en: "future", cn: "未来" },
      { en: "tomorrow", cn: "明天" },
      { en: "weekend", cn: "周末" },
      { en: "today", cn: "今天" },
      { en: "morning", cn: "早上" },
      { en: "afternoon", cn: "下午" },
      { en: "evening", cn: "晚上" },
      { en: "night", cn: "夜晚" },
      { en: "week", cn: "星期" },
      { en: "month", cn: "月" },
      { en: "year", cn: "年" },
      { en: "time", cn: "时间" },
      { en: "clock", cn: "时钟" },
      { en: "watch", cn: "手表" },
      { en: "early", cn: "早的" },
      { en: "late", cn: "晚的" },
      { en: "busy", cn: "忙碌的" },
      { en: "free", cn: "空闲的" },
      { en: "park", cn: "公园" },
      { en: "cinema", cn: "电影院" },
      { en: "zoo", cn: "动物园" },
      { en: "visit", cn: "参观" },
      { en: "see", cn: "看见" },
      { en: "play", cn: "玩" },
      { en: "do", cn: "做" },
      { en: "have", cn: "有" },
      { en: "go", cn: "去" }
    ]
  }
}

export const teenWords = {
  // 初高中阶段词汇 (应用与思辨阶段)
  healthy_life: {
    name: "健康生活",
    icon: "💪",
    words: [
      { en: "health", cn: "健康" },
      { en: "healthy", cn: "健康的" },
      { en: "diet", cn: "饮食" },
      { en: "food", cn: "食物" },
      { en: "exercise", cn: "锻炼" },
      { en: "sport", cn: "运动" },
      { en: "run", cn: "跑步" },
      { en: "swim", cn: "游泳" },
      { en: "gym", cn: "健身房" },
      { en: "mental", cn: "心理的" },
      { en: "stress", cn: "压力" },
      { en: "relax", cn: "放松" },
      { en: "sleep", cn: "睡眠" },
      { en: "habit", cn: "习惯" },
      { en: "smoke", cn: "吸烟" },
      { en: "alcohol", cn: "酒精" },
      { en: "drug", cn: "药物" },
      { en: "obesity", cn: "肥胖" },
      { en: "fit", cn: "健康的" },
      { en: "strong", cn: "强壮的" },
      { en: "energy", cn: "能量" },
      { en: "balance", cn: "平衡" },
      { en: "lifestyle", cn: "生活方式" },
      { en: "choice", cn: "选择" },
      { en: "prevent", cn: "预防" },
      { en: "disease", cn: "疾病" },
      { en: "doctor", cn: "医生" },
      { en: "patient", cn: "病人" },
      { en: "hospital", cn: "医院" },
      { en: "wellbeing", cn: "幸福感" }
    ]
  },

  technology_life: {
    name: "科技与生活",
    icon: "💻",
    words: [
      { en: "technology", cn: "科技" },
      { en: "computer", cn: "电脑" },
      { en: "internet", cn: "互联网" },
      { en: "smartphone", cn: "智能手机" },
      { en: "social media", cn: "社交媒体" },
      { en: "app", cn: "应用程序" },
      { en: "online", cn: "在线的" },
      { en: "offline", cn: "离线的" },
      { en: "digital", cn: "数字的" },
      { en: "information", cn: "信息" },
      { en: "connect", cn: "连接" },
      { en: "communicate", cn: "交流" },
      { en: "convenient", cn: "方便的" },
      { en: "efficient", cn: "高效的" },
      { en: "depend", cn: "依赖" },
      { en: "influence", cn: "影响" },
      { en: "positive", cn: "积极的" },
      { en: "negative", cn: "消极的" },
      { en: "cyberbullying", cn: "网络霸凌" },
      { en: "privacy", cn: "隐私" },
      { en: "safety", cn: "安全" },
      { en: "addiction", cn: "成瘾" },
      { en: "modern", cn: "现代的" },
      { en: "develop", cn: "发展" },
      { en: "innovation", cn: "创新" },
      { en: "artificial intelligence", cn: "人工智能" },
      { en: "robot", cn: "机器人" },
      { en: "future", cn: "未来" },
      { en: "trend", cn: "趋势" },
      { en: "impact", cn: "影响" }
    ]
  },

  environmental_issues: {
    name: "环境问题",
    icon: "🌍",
    words: [
      { en: "environment", cn: "环境" },
      { en: "environmental", cn: "环境的" },
      { en: "pollution", cn: "污染" },
      { en: "air pollution", cn: "空气污染" },
      { en: "water pollution", cn: "水污染" },
      { en: "plastic", cn: "塑料" },
      { en: "waste", cn: "废物" },
      { en: "recycle", cn: "回收" },
      { en: "protect", cn: "保护" },
      { en: "save", cn: "拯救" },
      { en: "energy", cn: "能源" },
      { en: "renewable", cn: "可再生的" },
      { en: "solar", cn: "太阳能" },
      { en: "wind", cn: "风能" },
      { en: "climate change", cn: "气候变化" },
      { en: "global warming", cn: "全球变暖" },
      { en: "planet", cn: "星球" },
      { en: "Earth", cn: "地球" },
      { en: "resource", cn: "资源" },
      { en: "sustainable", cn: "可持续的" },
      { en: "deforestation", cn: "森林砍伐" },
      { en: "species", cn: "物种" },
      { en: "extinct", cn: "灭绝" },
      { en: "green", cn: "绿色的" },
      { en: "clean", cn: "清洁的" },
      { en: "action", cn: "行动" },
      { en: "government", cn: "政府" },
      { en: "individual", cn: "个人" },
      { en: "responsibility", cn: "责任" },
      { en: "future", cn: "未来" }
    ]
  },

  cultural_differences: {
    name: "文化差异",
    icon: "🌏",
    words: [
      { en: "culture", cn: "文化" },
      { en: "cultural", cn: "文化的" },
      { en: "difference", cn: "差异" },
      { en: "custom", cn: "习俗" },
      { en: "tradition", cn: "传统" },
      { en: "value", cn: "价值观" },
      { en: "belief", cn: "信念" },
      { en: "respect", cn: "尊重" },
      { en: "understand", cn: "理解" },
      { en: "misunderstanding", cn: "误解" },
      { en: "communication", cn: "交流" },
      { en: "language", cn: "语言" },
      { en: "food", cn: "食物" },
      { en: "festival", cn: "节日" },
      { en: "religion", cn: "宗教" },
      { en: "family", cn: "家庭" },
      { en: "education", cn: "教育" },
      { en: "polite", cn: "礼貌的" },
      { en: "rude", cn: "粗鲁的" },
      { en: "gesture", cn: "手势" },
      { en: "global", cn: "全球的" },
      { en: "abroad", cn: "国外" },
      { en: "foreign", cn: "外国的" },
      { en: "integrate", cn: "融合" },
      { en: "diversity", cn: "多样性" },
      { en: "unique", cn: "独特的" },
      { en: "similar", cn: "相似的" },
      { en: "different", cn: "不同的" },
      { en: "accept", cn: "接受" },
      { en: "open-minded", cn: "开放的" }
    ]
  },

  career_planning: {
    name: "未来职业规划",
    icon: "🎯",
    words: [
      { en: "career", cn: "职业" },
      { en: "job", cn: "工作" },
      { en: "occupation", cn: "职业" },
      { en: "profession", cn: "专业" },
      { en: "future", cn: "未来" },
      { en: "dream", cn: "梦想" },
      { en: "goal", cn: "目标" },
      { en: "plan", cn: "计划" },
      { en: "university", cn: "大学" },
      { en: "college", cn: "学院" },
      { en: "major", cn: "专业" },
      { en: "subject", cn: "科目" },
      { en: "skill", cn: "技能" },
      { en: "ability", cn: "能力" },
      { en: "interest", cn: "兴趣" },
      { en: "experience", cn: "经验" },
      { en: "interview", cn: "面试" },
      { en: "resume", cn: "简历" },
      { en: "CV", cn: "简历" },
      { en: "apply", cn: "申请" },
      { en: "application", cn: "申请" },
      { en: "worker", cn: "工人" },
      { en: "doctor", cn: "医生" },
      { en: "engineer", cn: "工程师" },
      { en: "teacher", cn: "老师" },
      { en: "artist", cn: "艺术家" },
      { en: "salary", cn: "薪水" },
      { en: "successful", cn: "成功的" },
      { en: "challenge", cn: "挑战" },
      { en: "opportunity", cn: "机会" }
    ]
  },

  social_issues: {
    name: "社会热点",
    icon: "📰",
    words: [
      { en: "society", cn: "社会" },
      { en: "social", cn: "社会的" },
      { en: "issue", cn: "问题" },
      { en: "problem", cn: "问题" },
      { en: "teenager", cn: "青少年" },
      { en: "pressure", cn: "压力" },
      { en: "competition", cn: "竞争" },
      { en: "education", cn: "教育" },
      { en: "equality", cn: "平等" },
      { en: "volunteer", cn: "志愿者" },
      { en: "service", cn: "服务" },
      { en: "charity", cn: "慈善" },
      { en: "global", cn: "全球的" },
      { en: "event", cn: "事件" },
      { en: "news", cn: "新闻" },
      { en: "media", cn: "媒体" },
      { en: "opinion", cn: "观点" },
      { en: "view", cn: "观点" },
      { en: "discuss", cn: "讨论" },
      { en: "debate", cn: "辩论" },
      { en: "solve", cn: "解决" },
      { en: "solution", cn: "解决方案" },
      { en: "cause", cn: "原因" },
      { en: "effect", cn: "影响" },
      { en: "young", cn: "年轻的" },
      { en: "old", cn: "年老的" },
      { en: "generation", cn: "一代" },
      { en: "poverty", cn: "贫困" },
      { en: "wealth", cn: "财富" },
      { en: "gap", cn: "差距" }
    ]
  }
}

export const youngWords = {
  // 大学四六级阶段词汇 (应试与学术入门)
  education_issues: {
    name: "教育问题",
    icon: "🎓",
    words: [
      { en: "education", cn: "教育" },
      { en: "educational", cn: "教育的" },
      { en: "system", cn: "系统" },
      { en: "online", cn: "在线的" },
      { en: "traditional", cn: "传统的" },
      { en: "remote", cn: "远程的" },
      { en: "quality", cn: "质量" },
      { en: "equality", cn: "平等" },
      { en: "opportunity", cn: "机会" },
      { en: "resource", cn: "资源" },
      { en: "method", cn: "方法" },
      { en: "approach", cn: "方法" },
      { en: "critical thinking", cn: "批判性思维" },
      { en: "creativity", cn: "创造力" },
      { en: "exam-oriented", cn: "应试导向的" },
      { en: "quality-oriented", cn: "素质导向的" },
      { en: "value", cn: "价值" },
      { en: "purpose", cn: "目的" },
      { en: "reform", cn: "改革" },
      { en: "investment", cn: "投资" },
      { en: "government", cn: "政府" },
      { en: "private", cn: "私人的" },
      { en: "public", cn: "公共的" },
      { en: "access", cn: "获取" },
      { en: "gap", cn: "差距" },
      { en: "develop", cn: "发展" },
      { en: "potential", cn: "潜力" },
      { en: "lifelong", cn: "终身的" },
      { en: "scholar", cn: "学者" },
      { en: "academic", cn: "学术的" }
    ]
  },

  mental_health: {
    name: "心理健康",
    icon: "🧠",
    words: [
      { en: "mental", cn: "心理的" },
      { en: "psychological", cn: "心理学的" },
      { en: "health", cn: "健康" },
      { en: "stress", cn: "压力" },
      { en: "anxiety", cn: "焦虑" },
      { en: "depression", cn: "抑郁" },
      { en: "pressure", cn: "压力" },
      { en: "cope", cn: "应对" },
      { en: "manage", cn: "管理" },
      { en: "emotion", cn: "情感" },
      { en: "feeling", cn: "感觉" },
      { en: "resilience", cn: "韧性" },
      { en: "wellbeing", cn: "幸福感" },
      { en: "counseling", cn: "咨询" },
      { en: "therapy", cn: "治疗" },
      { en: "support", cn: "支持" },
      { en: "system", cn: "系统" },
      { en: "awareness", cn: "意识" },
      { en: "stigma", cn: "污名" },
      { en: "recognize", cn: "识别" },
      { en: "symptom", cn: "症状" },
      { en: "cause", cn: "原因" },
      { en: "factor", cn: "因素" },
      { en: "prevent", cn: "预防" },
      { en: "treatment", cn: "治疗" },
      { en: "healthy", cn: "健康的" },
      { en: "balance", cn: "平衡" },
      { en: "lifestyle", cn: "生活方式" },
      { en: "mindfulness", cn: "正念" },
      { en: "epidemic", cn: "流行病" }
    ]
  },

  globalization: {
    name: "全球化",
    icon: "🌐",
    words: [
      { en: "globalization", cn: "全球化" },
      { en: "global", cn: "全球的" },
      { en: "international", cn: "国际的" },
      { en: "worldwide", cn: "世界范围的" },
      { en: "economy", cn: "经济" },
      { en: "economic", cn: "经济的" },
      { en: "trade", cn: "贸易" },
      { en: "culture", cn: "文化" },
      { en: "integration", cn: "一体化" },
      { en: "interdependence", cn: "相互依赖" },
      { en: "cooperation", cn: "合作" },
      { en: "competition", cn: "竞争" },
      { en: "multinational", cn: "跨国的" },
      { en: "corporation", cn: "公司" },
      { en: "exchange", cn: "交换" },
      { en: "communication", cn: "交流" },
      { en: "technology", cn: "技术" },
      { en: "trend", cn: "趋势" },
      { en: "challenge", cn: "挑战" },
      { en: "opportunity", cn: "机会" },
      { en: "homogenization", cn: "同质化" },
      { en: "diversity", cn: "多样性" },
      { en: "local", cn: "本地的" },
      { en: "identity", cn: "身份" },
      { en: "border", cn: "边界" },
      { en: "free trade", cn: "自由贸易" },
      { en: "barrier", cn: "壁垒" },
      { en: "impact", cn: "影响" },
      { en: "benefit", cn: "好处" },
      { en: "drawback", cn: "缺点" }
    ]
  },

  urban_development: {
    name: "城市发展",
    icon: "🏙️",
    words: [
      { en: "urban", cn: "城市的" },
      { en: "urbanization", cn: "城市化" },
      { en: "city", cn: "城市" },
      { en: "development", cn: "发展" },
      { en: "growth", cn: "增长" },
      { en: "infrastructure", cn: "基础设施" },
      { en: "transportation", cn: "交通" },
      { en: "traffic", cn: "交通" },
      { en: "congestion", cn: "拥堵" },
      { en: "housing", cn: "住房" },
      { en: "problem", cn: "问题" },
      { en: "challenge", cn: "挑战" },
      { en: "solution", cn: "解决方案" },
      { en: "planning", cn: "规划" },
      { en: "smart city", cn: "智慧城市" },
      { en: "technology", cn: "技术" },
      { en: "sustainable", cn: "可持续的" },
      { en: "livable", cn: "宜居的" },
      { en: "environment", cn: "环境" },
      { en: "population", cn: "人口" },
      { en: "migrate", cn: "迁移" },
      { en: "suburb", cn: "郊区" },
      { en: "rural", cn: "农村的" },
      { en: "area", cn: "地区" },
      { en: "facility", cn: "设施" },
      { en: "public service", cn: "公共服务" },
      { en: "pollution", cn: "污染" },
      { en: "overcrowding", cn: "过度拥挤" },
      { en: "cost of living", cn: "生活成本" },
      { en: "metropolis", cn: "大都市" }
    ]
  },

  professional_ethics: {
    name: "职业道德",
    icon: "⚖️",
    words: [
      { en: "career", cn: "职业" },
      { en: "professional", cn: "专业的" },
      { en: "ethics", cn: "道德" },
      { en: "moral", cn: "道德的" },
      { en: "principle", cn: "原则" },
      { en: "conduct", cn: "行为" },
      { en: "behavior", cn: "行为" },
      { en: "responsibility", cn: "责任" },
      { en: "accountability", cn: "问责制" },
      { en: "integrity", cn: "诚信" },
      { en: "honesty", cn: "诚实" },
      { en: "fairness", cn: "公平" },
      { en: "equality", cn: "平等" },
      { en: "discrimination", cn: "歧视" },
      { en: "gender", cn: "性别" },
      { en: "race", cn: "种族" },
      { en: "opportunity", cn: "机会" },
      { en: "workplace", cn: "工作场所" },
      { en: "environment", cn: "环境" },
      { en: "balance", cn: "平衡" },
      { en: "burnout", cn: "倦怠" },
      { en: "motivation", cn: "动机" },
      { en: "satisfaction", cn: "满意度" },
      { en: "loyalty", cn: "忠诚" },
      { en: "corporate", cn: "企业的" },
      { en: "culture", cn: "文化" },
      { en: "leader", cn: "领导者" },
      { en: "leadership", cn: "领导力" },
      { en: "team", cn: "团队" },
      { en: "colleague", cn: "同事" }
    ]
  },

  information_age: {
    name: "信息时代",
    icon: "💾",
    words: [
      { en: "information", cn: "信息" },
      { en: "era", cn: "时代" },
      { en: "age", cn: "时代" },
      { en: "digital", cn: "数字的" },
      { en: "revolution", cn: "革命" },
      { en: "data", cn: "数据" },
      { en: "big data", cn: "大数据" },
      { en: "privacy", cn: "隐私" },
      { en: "security", cn: "安全" },
      { en: "cyber", cn: "网络的" },
      { en: "fake news", cn: "假新闻" },
      { en: "misinformation", cn: "错误信息" },
      { en: "media literacy", cn: "媒体素养" },
      { en: "critical thinking", cn: "批判性思维" },
      { en: "overload", cn: "过载" },
      { en: "filter", cn: "过滤" },
      { en: "bubble", cn: "泡沫" },
      { en: "algorithm", cn: "算法" },
      { en: "source", cn: "来源" },
      { en: "reliable", cn: "可靠的" },
      { en: "credibility", cn: "可信度" },
      { en: "verify", cn: "验证" },
      { en: "share", cn: "分享" },
      { en: "spread", cn: "传播" },
      { en: "influence", cn: "影响" },
      { en: "public opinion", cn: "公众舆论" },
      { en: "manipulate", cn: "操纵" },
      { en: "awareness", cn: "意识" },
      { en: "skill", cn: "技能" },
      { en: "digital divide", cn: "数字鸿沟" }
    ]
  }
}

export const adultWords = {
  arts_culture: {
    name: "艺术与文化",
    icon: "🎨",
    words: [
      { en: "art", cn: "艺术" },
      { en: "artistic", cn: "艺术的" },
      { en: "culture", cn: "文化" },
      { en: "cultural", cn: "文化的" },
      { en: "heritage", cn: "遗产" },
      { en: "government", cn: "政府" },
      { en: "fund", cn: "资助" },
      { en: "finance", cn: "财政" },
      { en: "subsidy", cn: "补贴" },
      { en: "role", cn: "角色" },
      { en: "function", cn: "功能" },
      { en: "education", cn: "教育" },
      { en: "creativity", cn: "创造力" },
      { en: "expression", cn: "表达" },
      { en: "identity", cn: "身份" },
      { en: "preserve", cn: "保护" },
      { en: "conservation", cn: "保护" },
      { en: "historical", cn: "历史的" },
      { en: "significance", cn: "意义" },
      { en: "value", cn: "价值" },
      { en: "aesthetic", cn: "美学的" },
      { en: "public", cn: "公共的" },
      { en: "access", cn: "接触" },
      { en: "promote", cn: "促进" },
      { en: "sponsor", cn: "赞助" },
      { en: "patronage", cn: "赞助" },
      { en: "monument", cn: "纪念碑" },
      { en: "artifact", cn: "文物" },
      { en: "gallery", cn: "画廊" },
      { en: "museum", cn: "博物馆" }
    ]
  },
  law_society: {
    name: "法律与社会",
    icon: "⚖️",
    words: [
      { en: "law", cn: "法律" },
      { en: "legal", cn: "法律的" },
      { en: "legislation", cn: "立法" },
      { en: "society", cn: "社会" },
      { en: "social", cn: "社会的" },
      { en: "juvenile", cn: "青少年" },
      { en: "delinquency", cn: "犯罪" },
      { en: "crime", cn: "犯罪" },
      { en: "criminal", cn: "罪犯" },
      { en: "offender", cn: "罪犯" },
      { en: "victim", cn: "受害者" },
      { en: "cause", cn: "原因" },
      { en: "factor", cn: "因素" },
      { en: "punishment", cn: "惩罚" },
      { en: "penalty", cn: "刑罚" },
      { en: "prison", cn: "监狱" },
      { en: "rehabilitation", cn: "改造" },
      { en: "deter", cn: "威慑" },
      { en: "prevent", cn: "预防" },
      { en: "purpose", cn: "目的" },
      { en: "justice", cn: "正义" },
      { en: "reform", cn: "改革" },
      { en: "system", cn: "制度" },
      { en: "enforce", cn: "执行" },
      { en: "authority", cn: "权威" },
      { en: "obey", cn: "遵守" },
      { en: "discipline", cn: "纪律" },
      { en: "moral", cn: "道德的" },
      { en: "ethical", cn: "伦理的" },
      { en: "contemporary", cn: "当代的" }
    ]
  },
  tech_ethics: {
    name: "科技伦理",
    icon: "🤖",
    words: [
      { en: "ethics", cn: "伦理" },
      { en: "ethical", cn: "伦理的" },
      { en: "technology", cn: "技术" },
      { en: "scientific", cn: "科学的" },
      { en: "innovation", cn: "创新" },
      { en: "genetic", cn: "基因的" },
      { en: "engineering", cn: "工程" },
      { en: "clone", cn: "克隆" },
      { en: "modification", cn: "改造" },
      { en: "artificial", cn: "人工的" },
      { en: "intelligence", cn: "智能" },
      { en: "robot", cn: "机器人" },
      { en: "automation", cn: "自动化" },
      { en: "space", cn: "太空" },
      { en: "exploration", cn: "探索" },
      { en: "experiment", cn: "实验" },
      { en: "dilemma", cn: "困境" },
      { en: "controversy", cn: "争议" },
      { en: "debate", cn: "辩论" },
      { en: "boundary", cn: "边界" },
      { en: "limit", cn: "限制" },
      { en: "regulation", cn: "规定" },
      { en: "control", cn: "控制" },
      { en: "risk", cn: "风险" },
      { en: "benefit", cn: "益处" },
      { en: "potential", cn: "潜在的" },
      { en: "consequence", cn: "后果" },
      { en: "future", cn: "未来" },
      { en: "humanity", cn: "人类" },
      { en: "moral", cn: "道德的" }
    ]
  },
  urbanization_heritage: {
    name: "城市化与遗产",
    icon: "🏛️",
    words: [
      { en: "urbanization", cn: "城市化" },
      { en: "urban", cn: "城市的" },
      { en: "development", cn: "发展" },
      { en: "expansion", cn: "扩张" },
      { en: "heritage", cn: "遗产" },
      { en: "historical", cn: "历史的" },
      { en: "architectural", cn: "建筑的" },
      { en: "preserve", cn: "保护" },
      { en: "conserve", cn: "保护" },
      { en: "protect", cn: "保护" },
      { en: "demolish", cn: "拆除" },
      { en: "destroy", cn: "破坏" },
      { en: "replace", cn: "替代" },
      { en: "modern", cn: "现代的" },
      { en: "infrastructure", cn: "基础设施" },
      { en: "skyscraper", cn: "摩天大楼" },
      { en: "landmark", cn: "地标" },
      { en: "identity", cn: "身份" },
      { en: "character", cn: "特色" },
      { en: "sacrifice", cn: "牺牲" },
      { en: "balance", cn: "平衡" },
      { en: "integrate", cn: "整合" },
      { en: "adaptive", cn: "适应性的" },
      { en: "reuse", cn: "重新利用" },
      { en: "policy", cn: "政策" },
      { en: "regulation", cn: "规定" },
      { en: "conflict", cn: "冲突" },
      { en: "progress", cn: "进步" },
      { en: "culture", cn: "文化" },
      { en: "sustainable", cn: "可持续的" }
    ]
  },
  globalization_impact: {
    name: "全球化影响",
    icon: "🌍",
    words: [
      { en: "globalization", cn: "全球化" },
      { en: "impact", cn: "影响" },
      { en: "effect", cn: "效果" },
      { en: "influence", cn: "影响" },
      { en: "international", cn: "国际的" },
      { en: "tourism", cn: "旅游业" },
      { en: "tourist", cn: "游客" },
      { en: "culture", cn: "文化" },
      { en: "homogenization", cn: "同质化" },
      { en: "diversity", cn: "多样性" },
      { en: "unique", cn: "独特的" },
      { en: "local", cn: "当地的" },
      { en: "tradition", cn: "传统" },
      { en: "custom", cn: "习俗" },
      { en: "multinational", cn: "跨国的" },
      { en: "corporation", cn: "公司" },
      { en: "economy", cn: "经济" },
      { en: "gap", cn: "差距" },
      { en: "disparity", cn: "差异" },
      { en: "wealth", cn: "财富" },
      { en: "poverty", cn: "贫困" },
      { en: "developed", cn: "发达的" },
      { en: "developing", cn: "发展中的" },
      { en: "nation", cn: "国家" },
      { en: "interdependence", cn: "相互依赖" },
      { en: "cooperation", cn: "合作" },
      { en: "conflict", cn: "冲突" },
      { en: "exchange", cn: "交流" },
      { en: "understanding", cn: "理解" },
      { en: "stereotype", cn: "刻板印象" }
    ]
  },
  government_role: {
    name: "政府角色",
    icon: "🏛️",
    words: [
      { en: "government", cn: "政府" },
      { en: "role", cn: "角色" },
      { en: "responsibility", cn: "责任" },
      { en: "function", cn: "功能" },
      { en: "public", cn: "公共的" },
      { en: "service", cn: "服务" },
      { en: "sector", cn: "部门" },
      { en: "fund", cn: "资助" },
      { en: "finance", cn: "财政" },
      { en: "tax", cn: "税收" },
      { en: "revenue", cn: "收入" },
      { en: "spend", cn: "支出" },
      { en: "investment", cn: "投资" },
      { en: "priority", cn: "优先" },
      { en: "healthcare", cn: "医疗" },
      { en: "education", cn: "教育" },
      { en: "infrastructure", cn: "基础设施" },
      { en: "welfare", cn: "福利" },
      { en: "system", cn: "制度" },
      { en: "regulation", cn: "规定" },
      { en: "control", cn: "控制" },
      { en: "policy", cn: "政策" },
      { en: "law", cn: "法律" },
      { en: "intervene", cn: "干预" },
      { en: "subsidy", cn: "补贴" },
      { en: "support", cn: "支持" },
      { en: "citizen", cn: "公民" },
      { en: "society", cn: "社会" },
      { en: "national", cn: "国家的" },
      { en: "local", cn: "地方的" }
    ]
  },
    
}